### ISSUE TITLE
dwm1001-dev USB interface

### ISSUE THREAD

**Issue by Seanmatthews** [Decawave/dwm1001-examples#1]
Do any of these examples demonstrate how to interface either a tag or a link via USB from a PC?

**Comment by pkettle** [comment]
Hi Sean, 
Your best bet is https://www.decawave.com/decaforum for support on this particular repo.

**Comment by YBDecawave** [comment]
Hi Sean,

Just wondering if you got to progress with the USB interface with the tag ? If not, maybe give a bit more detail about what you're trying to do. 

Thanks,
Yves
