### ISSUE TITLE
Array bound check error

### ISSUE THREAD

**Issue by azizbahri** [Decawave/dwm1001-examples#10]
Pretty sure the bound check here is reversed.

int dwt_setlocaldataptr(unsigned int index)
{
    // Check the index is within the array bounds
    **if (DWT_NUM_DW_DEV > index) // return error if index outside the array bounds**
    **{
        return DWT_ERROR ;
    }**

    pdw1000local = &dw1000local[index];

    return DWT_SUCCESS ;
}

**Comment by YBDecawave** [comment]
Hi Aziz,

What do you exactly mean ?

I guess index < DWT_NUM_DW_DEV  would be better for readability but the overall behavior is identical.

Thank you,
Regards
Yves

**Comment by azizbahri** [comment]
you are returning DWT_ERROR if  (index < DWT_NUM_DW_DEV) is true .

**Comment by YBDecawave** [comment]
Hi Aziz,

You are right.

This will be fixed in our next DW1000 api firmware release.

Thank you,
Yves
