### ISSUE TITLE
Porting Nrf52840

### ISSUE THREAD

**Issue by vivekalways** [Decawave/dwm1001-examples#12]
hi 
Is it possible that porting nrf52832 with nrf82840?

**Comment by YBDecawave** [comment]
Hi vivekwalways,

Yes it looks like the nrf82840 has all the required interface (a SPI for the dw1000 and i2c for the accelerator.)

Thanks
Yves

**Comment by vivekalways** [comment]
Hi, 
Thanks.. we did it
