### ISSUE TITLE
how I can work with DRTLS_Manager_R2.apk

### ISSUE THREAD

**Issue by Kingwulin** [Decawave/dwm1001-examples#13]
Hi Decawave team
I meet a problem that I have not the source code to work with the phone app DRTLS_Manager_R2.apk,would you please give me some sugguestion? 
thanks

**Comment by YBDecawave** [comment]
Hi,

The DRTLS_Manager_R2.apk is developed to work with PANS. Decawave does not provide source code for PANS.

The software hosted on this repository is not linked in anyway with the DRTLS application.

Please go through the DWM1001_Firmware_User_Guide and DWM1001_System_Overview_Performance guide for further details about PANS.

https://decaforum.decawave.com/

Thank you,
Yves
