### ISSUE TITLE
Frame filtering with multiple tags

### ISSUE THREAD

**Issue by 20chix** [Decawave/dwm1001-examples#4]
Hi 

I just bought 2 DWM1001-DEV, one tag and one anchor, they work perfectly fine with the provided example trough UART. I was wondering if anyone know how to filter multiples anchors data in one tag.
Will the data from all anchors be transmitted into one tag using the example project? 

Thanks in advance

**Comment by YBDecawave** [comment]
Hi 20chix,

The example provided on this repository and very basic, and there is no real concept of anchors but only initiator and responder. These examples cannot be use with more than one responder as there will be collisions. You need to implement a TDMA scheme  if you wish to use more than two nodes within a system.

Thank you,
Regards
Yves

**Comment by 20chix** [comment]
Thanks
