### ISSUE TITLE
General hardware instructions for beginners

### ISSUE THREAD

**Issue by FoufiDoumi** [Decawave/dwm1001-examples#5]
Hello there!

We are very interested in trying out those examples on our DWM1001-DEV boards (we got the MDEK1001 kit). We know that any change will erase the RTLS stack delivered with MDEK but this is what we need to do in order to take advantage of the DW1000 API, send our own messages, get timestamps, and generally build from there.

But, because we seriously are newbies, we will need all the help there is to guide us through reprogramming the boards and at least trying and testing the examples you provide.

Thank you!

**Comment by kendecawave** [comment]
The RTLS Stack (PANS) hex file is available for download from the decawave website, so you can always recover your MDEK to its initial factory state.
 
The DWM1001-Dev board comes with Segger J-Link on board. So you if you have Segger Embedded Studio IDE already installed all you need is a USB cable plugged i between the PC and the Dev board.
You can then easily compile, download and debug the example code.

 I suggest you post your support request on the Decawave forum -
https://www.decawave.com/decaforum/
