### ISSUE TITLE
Defined SPEED_OF_LIGHT ...

### ISSUE THREAD

**Issue by FoufiDoumi** [Decawave/dwm1001-examples#8]
Guys, I think there is a mistake in your code since you define the speed of light as 299702547 m/sec but it is actually 299792458 m/sec. ... That's a bit over 90Km difference. Did you actually intend to put the speed of light or you have changed it a bit to compensate for something and didn't explain why in the code's comments?

[https://en.wikipedia.org/wiki/Speed_of_light](https://en.wikipedia.org/wiki/Speed_of_light)

**Comment by YBDecawave** [comment]
Hi FoufiDoumi,

We are using the speed of light in the air, not in the vacuum, hereby the difference. For the small distance measured by UWB, it shouldn't have a large impact on the result.

Thank you,
Yves
