### ISSUE TITLE
BLE Example

### ISSUE THREAD

**Issue by avinashGonsalves** [Decawave/dwm1001-examples#9]
Do you have a BLE Example for this SDK as well?

**Comment by YBDecawave** [comment]
Hi Avimash,

Please refer to Nordic Semiconductor for a BLE example as the BLE is a Nordic IP.

https://www.nordicsemi.com/eng/Products/S132-SoftDevice

https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v14.2.0%2Fexamples_ble.html&cp=4_0_1_4_2

Thank you,
Regards
Yves
